import type { Metadata } from 'next'
import ContentHome from './contentHome';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Home({ params: { lang } }:any) {
  return (
    <ContentHome lang={lang} />
  );
}
